### PR TITLE
Move Events 1 API deprecated handlers to API v2 (classes) M31+

### PR DESCRIPTION
**Pull request by nadavkav**
Hi Bas,

We are using this beautiful plugin for a long time now, and have change it slightly, but nothing that can interest the community, except...

While migrating to Moodle 3.1, we changed the Events 1 API (libraries) to Events 2 API (classes)
I tried to take off all the code that was specific to what changed for our internal needs and kept the generic code that has to do with the API change.

After taking all the redundant code, I haven't tested it, but I think it works fine.

Please review it and see if you can integrate.

Thank you very much for this beautiful plugin!
Nadav

### CODE REVIEW

**Comment by michael-milette** [comment]
Is there any chance a Moodle 3.1 compatible version will be available soon?

**Comment by bmbrands** [comment]
Ooh I overlooked Nadav's contribution. Will review this soon and create a new version. Will schedule it for monday 17th.

**Comment by benchen71** [comment]
I couldn't get the patch to work.  However, I made the following changes to observer.php and got it working:

Line 32:
$user = \core_user::get_user($event->objectid);

Line 55:
$welcome = new \local_welcome\message();

**Comment by nadavkav** [comment]
I agree with @benchen71 . This patch is relatively old, 
and we have an updated version of it locally with above suggested changes, and some more.
I will find some time tomorrow to update this entire patch.

**Comment by bmbrands** [comment]
Hi Ben & Nadav, 

Thanks for you input! I'd be happy to merge any fixes that makes this work for 3.1!

**Pull request merged**
